#!/usr/bin/env bash
# PreToolUse hook: Edit | Write
# Blocks writing interfaces/*.pyi files unless a matching CRC card exists
# in plans/project-spec.md for the Protocol name derived from the filename.
# Skip if .iocane/validating sentinel exists (automated spec validation workflows).

# Skip during automated validation
if [ -f ".iocane/validating" ]; then
    exit 0
fi

INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | uv run python -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('tool_input', {}).get('file_path', ''))
except Exception:
    print('')
")

# Check if the target is an interfaces/*.pyi file
IS_INTERFACE=$(FILE_PATH="$FILE_PATH" uv run python -c "
import os, sys
p = os.path.normpath(os.environ['FILE_PATH']).replace('\\\\', '/')
parts = p.split('/')
# Match if 'interfaces' directory contains a .pyi file
if len(parts) >= 2 and parts[-2] == 'interfaces' and parts[-1].endswith('.pyi'):
    print('yes')
else:
    print('no')
")

if [ "$IS_INTERFACE" != "yes" ]; then
    exit 0
fi

# Derive PascalCase component name from filename
COMPONENT_NAME=$(FILE_PATH="$FILE_PATH" uv run python -c "
import os, re, sys
path = os.environ['FILE_PATH']
basename = os.path.basename(path)
stem = os.path.splitext(basename)[0]  # remove .pyi
# Convert snake_case to PascalCase
parts = stem.split('_')
pascal = ''.join(p.capitalize() for p in parts if p)
print(pascal)
")

if [ -z "$COMPONENT_NAME" ]; then
    exit 0
fi

# Check component-contracts.toml first (generated by /io-architect H-2c);
# fall back to project-spec.md regex if TOML is not yet present.
if [ -f "plans/component-contracts.toml" ]; then
    FOUND=$(COMPONENT_NAME="$COMPONENT_NAME" uv run python -c "
import sys, os, tomllib
component = os.environ['COMPONENT_NAME']
try:
    with open('plans/component-contracts.toml', 'rb') as f:
        data = tomllib.load(f)
    print('yes' if component in data.get('components', {}) else 'no')
except Exception:
    print('no')
")
elif [ -f "plans/project-spec.md" ]; then
    FOUND=$(COMPONENT_NAME="$COMPONENT_NAME" uv run python -c "
import re, sys, os
component = os.environ['COMPONENT_NAME']
try:
    content = open('plans/project-spec.md', encoding='utf-8').read()
    pattern = re.compile(
        r'###\s+' + re.escape(component) +
        r'|\*\*Component:\*\*\s*' + re.escape(component),
        re.MULTILINE
    )
    print('yes' if pattern.search(content) else 'no')
except Exception:
    print('no')
")
else
    echo "BLOCKED: Neither plans/component-contracts.toml nor plans/project-spec.md exists. Run /io-architect to design components before writing contracts." >&2
    exit 2
fi

if [ "$FOUND" != "yes" ]; then
    echo "BLOCKED: No contract entry for $COMPONENT_NAME. Design the component in /io-architect before writing the .pyi contract." >&2
    exit 2
fi

exit 0
